// <auto-generated />
using MVC_projeto.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_projeto.Migrations
{
    [DbContext(typeof(BandDbcontext))]
    [Migration("20230504172155_CreateTable")]
    partial class CreateTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVC_projeto.Models.BandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BandGenre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("genre");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("BandYear")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("band");
                });
#pragma warning restore 612, 618
        }
    }
}
